### ISSUE TITLE
请问界面中 set shape PC  的PC是指什么？

### ISSUE THREAD

**Issue by opptimus** [Great-Keith/bfm-visual-tool#1]
请问界面中 set shape PC  的PC是指什么？

**Comment by Bemfool** [comment]
PC指的是**P**rinciple **C**omponent的Basis。
在BFM模型中(或者说3DMM模型中)，使用PCA(Principle Component Analysis)来表示整个模型，换句话说，5万多个顶点可以通过更少数量的基来表示(比如BFM模型shape的基有199个)。
set shape PC实现的是将界面当中shape对应的ComboBox的值(1-199)对应的基的参数设置为Slider的值, 然后更新人脸。
同理Texture和Expression也是一样。

_[PS] 因为这个viewer是我自己拿来熟悉BFM以及可视后调试起来更为方便，所以很多地方写得并不general（可能如果想要在自己电脑上编译成功的话还需要改很多东西），所以如果有什么建议或问题欢迎来提，共勉。_

**Comment by opptimus** [comment]
感谢作者的精彩付出，我正在编译该界面，看来编译成功有难度
